name: Main Workflow
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codegen:
    name: Code Generation
    uses: ./.github/workflows/.codegen.yaml

  check:
    name: Check
    uses: ./.github/workflows/.check.yaml

  build:
    name: Build
    uses: ./.github/workflows/.build.yaml
    needs:
      - codegen

  tests:
    name: Tests
    uses: ./.github/workflows/.tests.yaml
    needs:
      - codegen

  release:
    name: Release
    uses: ./.github/workflows/.release.yaml
    needs:
      - check
      - build
      - tests
    if: ${{ github.repository == 'ts-graphviz/ts-graphviz' && github.ref == 'refs/heads/main' && success() }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
